[package]
name = "traffic-simulator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
netshield-common = { path = "../common" }
netshield-packet-parser = { path = "../packet-parser" }
netshield-detection = { path = "../detection" }
clap.workspace = true
rand.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
reqwest = { version = "0.12", features = ["json"] }
base64 = "0.22"
serde_json.workspace = true

[lints]
workspace = true
